# https://github.com/drduh/YubiKey-Guide#ssh
- apt:
    pkg:
    - lsb-release 
    - wget 
    - apt-transport-https
  become: yes

- apt_key:
    url: https://packages.riot.im/riot-release-key.asc
    state: present
  become: yes

- apt_repository:
    repo: deb https://packages.riot.im/debian/ {{ ansible_distribution_release }} main
    state: present

- apt:
    pkg:
    - riot-web
    update_cache: yes